services:
  - type: web
    name: shopvana
    env: python
    buildCommand: "./render-build.sh"
    startCommand: "gunicorn shopvana.wsgi:application --chdir shopvana --bind 0.0.0.0:$PORT"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DJANGO_SUPERUSER_USERNAME
        sync: false
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false
      - key: DJANGO_SUPERUSER_EMAIL
        sync: false
    releaseCommand: >
      python shopvana/manage.py migrate &&
      python shopvana/manage.py collectstatic --noinput &&
      python shopvana/manage.py shell -c "
      from django.contrib.auth import get_user_model;
      import os, sys;
      User = get_user_model();
      username=os.environ['DJANGO_SUPERUSER_USERNAME'];
      email=os.environ['DJANGO_SUPERUSER_EMAIL'];
      password=os.environ['DJANGO_SUPERUSER_PASSWORD'];
      user, created = User.objects.get_or_create(username=username, defaults={'email': email});
      user.is_active = True
      user.is_staff = True
      user.is_superuser = True
      user.set_password(password)
      user.save()
      msg = f'>>> Superuser {username} active={user.is_active} staff={user.is_staff} superuser={user.is_superuser}'
      print(msg)
      sys.stdout.flush()
      "