# Generated by Django 4.2.21 on 2025-07-28 21:27

import django.contrib.auth.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the user.', primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(help_text='Email address of the user.', max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, help_text='First name of the user.', max_length=30)),
                ('last_name', models.CharField(blank=True, help_text='Last name of the user.', max_length=30)),
                ('username', models.CharField(help_text='Unique username for the user.', max_length=150, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether the user account is active.')),
                ('is_staff', models.BooleanField(default=False, help_text='Indicates whether the user can log into the admin site.')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer'), ('vendor', 'Vendor')], default='customer', help_text='Role of the user in the system.', max_length=10)),
                ('date_joined', models.DateTimeField(auto_now_add=True, help_text='Date and time when the user joined.')),
                ('last_login', models.DateTimeField(blank=True, help_text="Date and time of the user's last login.", null=True)),
                ('password', models.CharField(help_text='Password for the user account.', max_length=128)),
                ('profile_picture', models.ImageField(blank=True, help_text='Profile picture of the user.', null=True, upload_to='profile_pictures/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='shopvana_user_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='shopvana_user_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-date_joined'],
                'indexes': [models.Index(fields=['email'], name='user_email_idx'), models.Index(fields=['date_joined'], name='user_date_joined_idx'), models.Index(fields=['role'], name='user_role_idx'), models.Index(fields=['username'], name='user_username_idx')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('email',), name='unique_user_email'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('username',), name='unique_user_username'),
        ),
    ]
