# Generated by Django 4.2.21 on 2025-08-13 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['order_id'], name='shopvana_re_order_i_bd03bb_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user_id'], name='shopvana_re_user_id_2b19bc_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['created_at'], name='shopvana_re_created_2b7331_idx'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(check=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='rating_between_1_and_5'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('order_id', 'user_id')},
        ),
    ]
