# Generated by Django 4.2.21 on 2025-08-10 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orderitem_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='review',
            name='shopvana_re_product_0cb111_idx',
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='review',
            name='order_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='orders.orderitem'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('order_id', 'user_id')},
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['order_id'], name='shopvana_re_order_i_bd03bb_idx'),
        ),
        migrations.RemoveField(
            model_name='review',
            name='product_id',
        ),
    ]
