# Generated by Django 4.2.21 on 2025-08-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_wallet_alter_payment_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='checkout_request_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='mpesa_receipt_number',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='wallet',
        ),
        migrations.AddField(
            model_name='payment',
            name='chapa_tx_ref',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('chapa_card', 'Chapa Card'), ('chapa_mobile', 'Chapa Mobile')], max_length=50),
        ),
    ]
