# Generated by Django 4.2.21 on 2025-08-13 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('wishlist_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Wishlists',
                'db_table': 'shopvana_wishlist',
                'ordering': ['-added_on'],
            },
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL)),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wishlists.wishlist')),
            ],
            options={
                'verbose_name_plural': 'Wishlist Items',
                'db_table': 'shopvana_wishlist_item',
                'ordering': ['-added_on'],
                'indexes': [models.Index(fields=['wishlist'], name='shopvana_wi_wishlis_7ffc7e_idx'), models.Index(fields=['product'], name='shopvana_wi_product_0d327e_idx'), models.Index(fields=['user'], name='shopvana_wi_user_id_ddd45a_idx'), models.Index(fields=['added_on'], name='shopvana_wi_added_o_68edde_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='wishlistitem',
            constraint=models.UniqueConstraint(fields=('wishlist', 'product'), name='unique_wishlist_item_per_wishlist'),
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['user_id'], name='shopvana_wi_user_id_fd8178_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['added_on'], name='shopvana_wi_added_o_49e39c_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['name'], name='shopvana_wi_name_c50472_idx'),
        ),
        migrations.AddConstraint(
            model_name='wishlist',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_wishlist_item_per_user'),
        ),
    ]
