# Generated by Django 4.2.21 on 2025-08-10 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderitem_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='status',
            new_name='item_status',
        ),
    ]
