# Generated by Django 4.2.21 on 2025-08-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_rename_status_orderitem_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_window_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ready_for_payment',
            field=models.BooleanField(default=False),
        ),
    ]
